### ISSUE TITLE
datamancer breaks nim CI

### ISSUE THREAD

**Issue by timotheecour** [SciNim/Datamancer#10]
@Vindaar  
how come `nimble search datamancer` doesn't list this?
also:
https://github.com/nim-lang/Nim/pull/18384/checks?check_run_id=2980455174
```
PASS: [7/35] fusion c                                                     (20.13 sec)
  FAIL: [8/35] ggplotnim c                                                  (59.81 sec)
  Test "ggplotnim" in category "nimble-packages"
  Failure: reBuildFailed
  nim c -d:noCairo -r tests/tests.nim
  Hint: used config file '/Users/runner/work/Nim/Nim/config/nim.cfg' [Conf]
  Hint: used config file '/Users/runner/work/Nim/Nim/config/config.nims' [Conf]
  Hint: used config file '/Users/runner/work/Nim/Nim/pkgstemp/ggplotnim/tests/config.nims' [Conf]
  .........................................................................................................................
  Compiling draw as a dummy proc
  .......
  /Users/runner/.nimble/pkgs/nimblas-0.2.2/nimblas/private/common.nim(50, 7) Hint: Using BLAS library with name: libblas.dylib [User]
  ........................................................................................................................
  /Users/runner/.nimble/pkgs/nimlapack-0.2.0/nimlapack.nim(19, 7) Hint: Using LAPACK library with name: liblapack.dylib [User]
  ........................................................................
  /Users/runner/.nimble/pkgs/datamancer-0.1.7/datamancer/dataframe.nim(1435, 29) template/generic instantiation of `{}` from here
  /Users/runner/.nimble/pkgs/datamancer-0.1.7/datamancer/formula.nim(818, 12) Warning: What kind? nnkIdent in node false [User]
  /Users/runner/.nimble/pkgs/datamancer-0.1.7/datamancer/dataframe.nim(1435, 29) template/generic instantiation of `{}` from here
  /Users/runner/.nimble/pkgs/datamancer-0.1.7/datamancer/formula.nim(818, 12) Warning: What kind? nnkBracketExpr in node df[localCol][idx] [User]
  FormulaNode(name: "(== isNull(df[localCol][idx]).toBool false)",
              colName: "(== isNull(df[localCol][idx]).toBool false)",
              kind: fkVector, resType: toColKind(type(bool)), fnV: proc (
      df: DataFrame): Column =
    let localColT = df[localCol, Value]
    var res = newTensor[bool](df.len)
    for idx in 0 ..< df.len:
      res[idx] = isNull(localColT[idx]).toBool == false
    result = toColumn res)
  .....
  /Users/runner/work/Nim/Nim/pkgstemp/ggplotnim/src/ggplotnim/ggplot_types.nim(509, 3) Error: not all cases are covered; missing: {fkNone}
  
  PASS: [9/35] httpauth c                                                   ( 7.15 sec)
```

**Comment by Vindaar** [comment]
1. This isn't a `datamancer` issue, but a `ggplotnim` one. The `datamancer` output you see there is still just a bunch of macro output that I print. It's the result of a `f{}` macro.
2. The underlying issue has already been fixed here: 
  https://github.com/Vindaar/ggplotnim/commit/989a8b0704b1b90a28a04ae64d1b35174c0ae8a0

No idea why the CI isn't picking up `ggplotnim` version `v0.4.3` though. It was tagged here:
https://github.com/Vindaar/ggplotnim/commit/fed986c1a2644061bd35b780f5efe84f6e086d6a

> how come nimble search datamancer doesn't list this?

Uhm, also no idea. Let me check. It was merged into `packages.json` here:
https://github.com/nim-lang/packages/commit/9c49e83e97f428de746ea7f240e0a06b59d352bf

I have the bad feeling nimble is treating the URL as case sensitive. Because I noticed that my PR to the packages repo includes lowercase names in the URL... I'll make a PR to see if that fixes at least this problem.
It's very weird though, because installing `datamancer` as a dependency in CI via nimble works perfectly fine.

**Comment by Vindaar** [comment]
Uhm, I can't even install any of my other packages using `nimble` anymore. No idea what got screwed up in the packages.json file or wherever.

**Comment by Vindaar** [comment]
Yeah, something is borked. `nimble list` only lists 311 packages.

**Comment by Vindaar** [comment]
Nevermind the datamancer nimble stuff. My nimble installation was borked. Works fine for me.
