### ISSUE TITLE
datamancer tests doesn't work with `-d:nimPreviewFloatRoundtrip`

### ISSUE THREAD

**Issue by ringabout** [SciNim/Datamancer#72]
Hi, in https://github.com/nim-lang/Nim/pull/24217, I'm trying to make `-d:nimPreviewFloatRoundtrip` the default. It seems to break some float tests:

```
/home/runner/work/Nim/Nim/pkgstemp/datamancer/tests/testParse.nim(124, 31): Check failed: classify(floatBuf) == fcNormal
2024-10-03T12:04:21.2772069Z     classify(floatBuf) was fcNan
2024-10-03T12:04:21.2772195Z     fcNormal was fcNormal
2024-10-03T12:04:21.2772436Z   [FAILED] Valid float values with separator
```

ref https://github.com/nim-lang/Nim/actions/runs/11161348816/job/31023719357?pr=24217

**Comment by Vindaar** [comment]
Hey!

Sorry, didn't see this before. I just noticed this myself while working on https://github.com/SciNim/Datamancer/pull/73.

I fixed it there. The reason was that I specifically had a `when defined(nimPreviewFloatRoundtrip)` case in there. With it becoming the default, it now chose the old, *wrong* branch of the code and not the correct one for it.

**Comment by ringabout** [comment]
@Vindaar Awesome!

**Comment by ringabout** [comment]
When https://github.com/nim-lang/Nim/pull/24300 is merged, `nimHasDefaultFloatRoundtrip` will be available for conditional testing
